export const SUPPORTED_CURRENCIES = [
  { code: 'NGN', type: 'fiat', name: 'Nigerian Naira' },
  { code: 'USDT', type: 'crypto', name: 'Tether' },
  { code: 'BTC', type: 'crypto', name: 'Bitcoin' },
  { code: 'ETH', type: 'crypto', name: 'Ethereum' },
  { code: 'BNB', type: 'crypto', name: 'Binance Coin' },
  { code: 'SOL', type: 'crypto', name: 'Solana' },
  { code: 'MATIC', type: 'crypto', name: 'Polygon' },
  { code: 'XRP', type: 'crypto', name: 'Ripple' },
  { code: 'DOGE', type: 'crypto', name: 'Dogecoin' },
  { code: 'ADA', type: 'crypto', name: 'Cardano' },
  { code: 'DOT', type: 'crypto', name: 'Polkadot (DOT)' },
  { code: 'LTC', type: 'crypto', name: 'Litecoin (LTC)' },
  { code: 'LINK', type: 'crypto', name: 'Chainlink (LINK)' },
  { code: 'BCH', type: 'crypto', name: 'Bitcoin Cash (BCH)' },
  { code: 'AAVE', type: 'crypto', name: 'Aave (AAVE)' },
  { code: 'ALGO', type: 'crypto', name: 'Algorand (ALGO)' },
  { code: 'NEAR', type: 'crypto', name: 'NEAR Protocol (NEAR)' },
  { code: 'FIL', type: 'crypto', name: 'Filecoin (FIL)' },
  { code: 'SAND', type: 'crypto', name: 'The Sandbox (SAND)' },
  { code: 'MANA', type: 'crypto', name: 'Decentraland (MANA)' },
  { code: 'APE', type: 'crypto', name: 'ApeCoin (APE)' },
  { code: 'SHIB', type: 'crypto', name: 'Shiba Inu (SHIB)' },
  { code: 'SUI', type: 'crypto', name: 'Sui (SUI)' },
  { code: 'INJ', type: 'crypto', name: 'Injective (INJ)' },
  { code: 'ARB', type: 'crypto', name: 'Arbitrum (ARB)' },
  { code: 'TON', type: 'crypto', name: 'Toncoin (TON)' },
  { code: 'RNDR', type: 'crypto', name: 'Render Token (RNDR)' },
  { code: 'STX', type: 'crypto', name: 'Stacks (STX)' },
  { code: 'GRT', type: 'crypto', name: 'The Graph (GRT)' },
  { code: 'TRUMP', type: 'crypto', name: 'Trump Token (TRUMP)' },
  { code: 'UNI', type: 'crypto', name: 'Uniswap (UNI)' },
  { code: 'AVAX', type: 'crypto', name: 'Avalanche (AVAX)' },
  { code: 'ATOM', type: 'crypto', name: 'Cosmos (ATOM)' },
  { code: 'CAKE', type: 'crypto', name: 'PancakeSwap (CAKE)' },
  { code: 'COMP', type: 'crypto', name: 'Compound (COMP)' },
  { code: 'CRV', type: 'crypto', name: 'Curve DAO (CRV)' },
  { code: 'DAI', type: 'crypto', name: 'Dai (DAI)' },
  { code: 'ENJ', type: 'crypto', name: 'Enjin Coin (ENJ)' },
  { code: 'FTM', type: 'crypto', name: 'Fantom (FTM)' },
  { code: 'GALA', type: 'crypto', name: 'Gala (GALA)' },
  { code: 'HBAR', type: 'crypto', name: 'Hedera (HBAR)' },
  { code: 'ICP', type: 'crypto', name: 'Internet Computer (ICP)' },
  { code: 'KCS', type: 'crypto', name: 'KuCoin Token (KCS)' },
  { code: 'LDO', type: 'crypto', name: 'Lido DAO (LDO)' },
  { code: 'MASK', type: 'crypto', name: 'Mask Network (MASK)' },
  { code: 'MKR', type: 'crypto', name: 'Maker (MKR)' },
  { code: 'NEO', type: 'crypto', name: 'NEO (NEO)' },
  { code: 'ONE', type: 'crypto', name: 'Harmony (ONE)' },
  { code: 'OP', type: 'crypto', name: 'Optimism (OP)' },
  { code: 'PEPE', type: 'crypto', name: 'Pepe (PEPE)' },
  { code: 'QNT', type: 'crypto', name: 'Quant (QNT)' },
  { code: 'RUNE', type: 'crypto', name: 'THORChain (RUNE)' },
  { code: 'SNX', type: 'crypto', name: 'Synthetix (SNX)' },
  { code: 'THETA', type: 'crypto', name: 'Theta Network (THETA)' },
  { code: 'VET', type: 'crypto', name: 'VeChain (VET)' },
  { code: 'WAVES', type: 'crypto', name: 'Waves (WAVES)' },
  { code: 'XDC', type: 'crypto', name: 'XDC Network (XDC)' },
  { code: 'XEC', type: 'crypto', name: 'eCash (XEC)' },
  { code: 'XEM', type: 'crypto', name: 'NEM (XEM)' },
  { code: 'XLM', type: 'crypto', name: 'Stellar (XLM)' },
  { code: 'XTZ', type: 'crypto', name: 'Tezos (XTZ)' },
  { code: 'ZEC', type: 'crypto', name: 'Zcash (ZEC)' },
  { code: 'ZIL', type: 'crypto', name: 'Zilliqa (ZIL)' }
];
