import {
  Loader2,
  Mail,
  User,
  Lock,
  Key,
  LogOut,
  Settings,
  CreditCard,
  Wallet,
  BarChart,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  SunMedium,
  Trash,
  Twitter,
  User2,
  X,
  Copy,
  Download,
  Upload,
  Bitcoin,
  DollarSign,
  RefreshCw,
  Calculator,
  ArrowUpDown,
  ChartBar,
  Info,
  Shield,
  Sun,
  Search,
  Eye,
  Bell,
  History,
  Inbox,
  UserCheck,
  Sparkles,
  TrendingUp,
  LayoutGrid,
  List,
  type LucideIcon,
  type LucideProps,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Wallet,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: HelpCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  mail: Mail,
  lock: Lock,
  key: Key,
  logout: LogOut,
  wallet: Wallet,
  chart: ChartBar,
  check: Check,
  copy: Copy,
  download: Download,
  upload: Upload,
  bitcoin: Bitcoin,
  ethereum: Wallet,
  dollar: DollarSign,
  naira: DollarSign,
  refresh: RefreshCw,
  calculator: Calculator,
  arrowUpDown: ArrowUpDown,
  info: Info,
  shield: Shield,
  search: Search,
  file: File,
  eye: Eye,
  bell: Bell,
  history: History,
  inbox: Inbox,
  userCheck: UserCheck,
  sparkles: Sparkles,
  trendingUp: TrendingUp,
  grid: LayoutGrid,
  list: List,
  google: ({ ...props }: LucideProps) => (
    <svg
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="google"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 488 512"
      {...props}
    >
      <path
        fill="currentColor"
        d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"
      ></path>
    </svg>
  ),
  twitter: Twitter,
} as const 